### ISSUE TITLE
Error0003: Daemon process is not (yet) running

### ISSUE THREAD

**Issue by Pilaarbijter** [Woersty/LoxBerry-Plugin-BLE-Scanner#40] opened 2021-07-02 12:24 UTC
Hello,

I installed the plugin and I get the following error:
![error](https://user-images.githubusercontent.com/86836014/124274051-182ea780-db41-11eb-8b34-95d69a122c88.jpg)
![log](https://user-images.githubusercontent.com/86836014/124274065-1c5ac500-db41-11eb-844e-68ebcb7a4626.jpg)

Any advise on this?

I'm using an ASUS usb bluetooth dongle that works fine on my pc and is recognized in the Loxberry system information.

Thanks in advance

**Comment by Woersty** [comment] 2021-07-03 07:54
Duplicate of #35 and #38

**Closed as completed** 2021-07-03 07:54 UTC
